#!/bin/bash
apt-get update -y
apt-get install -y apache2
systemctl enable apache2
systemctl start apache2

# Custom index.html
echo "<h1>Welcome to $(hostname -f) - EC2 Web Server</h1>" > /var/www/html/index.html
